eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: userservice
          uri: http://localhost:9098
          predicates:
            - Path=/user/**
        - id: movieservice
          uri: http://localhost:9099
          predicates:
            - Path=/movie/**
        - id: reviewservice
          uri: http://localhost:9101
          predicates:
            - Path=/review/**
        - id: recommedservice
          uri: http://localhost:9102
          predicates:
            - Path=/recommend/**

