
spring:
  application:
    name: movieservice
  config:
    import: optional:configserver:http://localhost:8888

#server:
#  port: 2238
#
#spring:
#  application:
#    name: Movie-Service
#  datasource:
#    url: jdbc:mysql://localhost:3306/movie
#    username: root
#    password: pass@word1
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true
